### ISSUE TITLE
Set background color for unselected label

### ISSUE THREAD

**Issue by ruslankmlv** [enfluid/apple-switch-control#25]
Setting background color on UILabel to nil makes it black, not white. As I understand, label gets a white default (nil) background color when using `init?(coder: NSCoder)`, so we need to set it explicitly to white color, since we're initializing it with `init(frame: .zero)`

**Comment by rudolf-adamkovic** [comment]
@ruslankmlv But that won't work when the switch needs to be transparent, e.g. in the navigation bar, etc. Right? If that's the case, why not use clear color instead?

**Comment by rudolf-adamkovic** [comment]
>  Right? If that's the case, why not use clear color instead?

Answered in #28.

CC: @ruslankmlv
